### ISSUE TITLE
Timezone data error

### ISSUE THREAD

**Issue by toqueteos** [9uuso/timezone#2]
This doesn't seem right: `{"America/Cordoba", "ES", "Spain"}` [(source)](https://github.com/9uuso/timezone/blob/9f4f58e4c582642705b7dfb22b3f68dae30b7bb7/locations.go#L108) according to http://www.timezoneconverter.com/cgi-bin/zoneinfo.tzc?s=default&tz=America/Cordoba it should be `Country: "AR"`.

**Comment by jhvst** [comment]
You are right. There were some cases which I had to go trough by hand and this one I got wrong. I must have had Googled Cordoba and just think it's a place in Spain.

Anyhow, thank you for letting me know. If you want to submit a PR and earn Internet points, feel free to do so! Alternatively I can commit the change myself.

**Comment by toqueteos** [comment]
https://github.com/9uuso/timezone/pull/3 The Internet points offer is tempting :laughing: but I was just curious because I'm about to use this in production I had to check first and my first test failed :sob: 

EDIT: I accidentally a couple words.

**Comment by jhvst** [comment]
Oh, it seems the DST change in Finland caused the tests to fail. I fixed the issue with afc42cbced3d915eda2459d78b6ad8f04ad8694c.

Anyhow, thank you for letting me know about the problem!

If you find any more, please do let me know! Improvements are always welcome!
